### PR TITLE
Refactoring, upgrading, API V2

### PR DESCRIPTION
**Pull request by b4dnewz**
Hi, I've used your module for a project and it works really good, but I decided few days ago to upgrade it to the V2 of the api and do a total refactoring of the code.

I removed most of the dependencies, right now it has just one: `request` for the http calls.
I've added linters, security checks and more, completely rebuilt the tests to use `nock` to mock the http responses.

I changed all the methods to match the new Hunter API, as much as i could.

I've also added travis and coveralls configurations.

I hope you'll like these changes, please let me know.

### CODE REVIEW

**Comment by b4dnewz** [comment]
Tests are failing because of this: https://nodesecurity.io/advisories/525
Regex DDos vuln in one of request dependencies, I'll switch it to axios or fetch to fix the issue.

**Comment by b4dnewz** [comment]
@kessiler please consider this PR, it still can be improved but right now I guess is ok, i'm already using it an a project so I will actively maintain it.

Many thanks in advance.

**Comment by kessiler** [comment]
Nice work @b4dnewz 
Can you bump the version to 2.0? Also, add some instructions how to upgrade from v1 to v2?

**Comment by b4dnewz** [comment]
@kessiler yup, I'll do it tomorrow afternoon and I'll push it again with the correct documentation, changelog and upgrade notice

**Comment by kessiler** [comment]
Great, @b4dnewz.
I'll also add you as a contributor here. :)

**Comment by b4dnewz** [comment]
thanks, soon I'll add support for the Resources API like [leads](https://hunter.io/api/v2/docs#leads), too.
I hope one day this module will be quoted on Hunter.io website as "unofficial node client", once is done

**Comment by b4dnewz** [comment]
I'm not sure if the upgrade section is clear enough, I'll take some time next days to think the best way to write the documentation to allow users to use both API and module versions and have a guide for that.

**Comment by kessiler** [comment]
hey @b4dnewz, did you give up here?
I thought I added you as contributor ;) - sorry about that

**Comment by b4dnewz** [comment]
yup, I made too many changes I decided to move in another package directly

**Pull request closed without merging**
